# Generated by Django 3.1.5 on 2021-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, default=0, verbose_name='온도')),
                ('humidity', models.FloatField(blank=True, default=0, verbose_name='습도')),
                ('on_air_conditioner', models.BooleanField(default=False, verbose_name='에어컨 켜짐여부')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='기록시간')),
            ],
            options={
                'verbose_name': 'conditionrecord',
                'verbose_name_plural': 'conditionrecords',
                'ordering': ['id'],
            },
        ),
    ]
